### ISSUE TITLE
Events --> Select Skin Dropdown

### ISSUE THREAD

**Issue by jonfen** [evanfarrar/opensprints#28]
While you can assign a skin to the entire software, it would be valuable to assign a skin to a particular event, otherwise it chooses what is in the main configuration as the default.

That way promoters can put on multiple events for multiple sponsors.

**Comment by evanfarrar** [comment]
Ideally, wouldn't the promoter use one event per promotion? So how does this save anything, since they would create an event, assign a skin, and then never go back and run that event again?

We could set up a "clients" list  or something then specify the sponsors for an event and automatically pull up a skin for the sponsor if it exists...but that's thinking waaay too far in advance on this issue. As far as we can tell, only a few users have been savvy enough to make one customization to the look and feel, let alone a new one for every sponsor they encounter. I wrote this crap and I've had about two sponsors who cared enough to throw a background or logo up there.
